-- AlterTable
ALTER TABLE `payments` ADD COLUMN `bankTranId` VARCHAR(191) NULL,
    ADD COLUMN `cardBrand` VARCHAR(191) NULL,
    ADD COLUMN `cardIssuer` VARCHAR(191) NULL,
    ADD COLUMN `cardType` VARCHAR(191) NULL,
    ADD COLUMN `errorReason` VARCHAR(191) NULL,
    ADD COLUMN `gatewayUrl` VARCHAR(191) NULL,
    ADD COLUMN `validationId` VARCHAR(191) NULL,
    MODIFY `method` ENUM('CREDIT_CARD', 'DEBIT_CARD', 'PAYPAL', 'BANK_TRANSFER', 'CASH', 'SSLCOMMERZ', 'OTHER') NOT NULL DEFAULT 'SSLCOMMERZ';
