-- AlterTable
ALTER TABLE `payments` MODIFY `method` ENUM('SSLCOMMERZ', 'CUSTOM', 'BANK_TRANSFER', 'CREDIT_CARD', 'DEBIT_CARD', 'MOBILE_BANKING', 'INTERNET_BANKING', 'CASH', 'OTHER') NOT NULL DEFAULT 'SSLCOMMERZ';
